db.books.insert([
  {'title': 'Harry Poter',
    'genre': 'Fantasy',
    'author': 'J.K. Rolling',
    'read': true},
  {'title': 'Origin',
    'genre': 'Thriller',
    'author': 'Dan Brown',
    'read': true},
  {'title': 'The Lord of The Rings',
    'genre': 'Fantasy',
    'author': 'R.R Tolkien',
    'read': true},
  {'title': 'El hombre en busca de sentido',
    'genre': 'Sociologia',
    'author': 'Viktor Frankl',
    'read': true},
]);
