db.users.insert([{
  'firsName': 'Jerome',
  'lastName': 'Vallerine',
  'userName': 'jvallerine0',
  'email': 'jvallerine0@nhs.uk',
  'address': '87002 Bellgrove Parkway',
  'phone': '6386660439',
}, {
  'firsName': 'Henrietta',
  'lastName': 'Sadler',
  'userName': 'hsadler1',
  'email': 'hsadler1@behance.net',
  'address': '2 Warner Way',
  'phone': '7096193797',
}, {
  'firsName': 'Nicole',
  'lastName': 'Hay',
  'userName': 'nhay2',
  'email': 'nhay2@lycos.com',
  'address': '7440 Armistice Alley',
  'phone': '5995858740',
}, {
  'firsName': 'Damien',
  'lastName': 'Manuele',
  'userName': 'dmanuele3',
  'email': 'dmanuele3@ucoz.com',
  'address': '0 Grayhawk Avenue',
  'phone': '5766518933',
}, {
  'firsName': 'Rhiamon',
  'lastName': 'Beney',
  'userName': 'rbeney4',
  'email': 'rbeney4@virginia.edu',
  'address': '970 Mockingbird Terrace',
  'phone': '7629524586',
}, {
  'firsName': 'Danice',
  'lastName': 'Moncrefe',
  'userName': 'dmoncrefe5',
  'email': 'dmoncrefe5@va.gov',
  'address': '25 Namekagon Court',
  'phone': '8206172544',
}, {
  'firsName': 'Viviana',
  'lastName': 'Pilch',
  'userName': 'vpilch6',
  'email': 'vpilch6@webs.com',
  'address': '5 Mallory Trail',
  'phone': '4368352789',
}, {
  'firsName': 'Shaun',
  'lastName': 'Hughf',
  'userName': 'shughf7',
  'email': 'shughf7@baidu.com',
  'address': '3 Upham Parkway',
  'phone': '7499778424',
}, {
  'firsName': 'Elton',
  'lastName': 'Giametti',
  'userName': 'egiametti8',
  'email': 'egiametti8@dailymotion.com',
  'address': '40264 Warbler Way',
  'phone': '7602884904',
}, {
  'firsName': 'Auberta',
  'lastName': 'Menilove',
  'userName': 'amenilove9',
  'email': 'amenilove9@ftc.gov',
  'address': '5311 Texas Court',
  'phone': '3269480842',
}, {
  'firsName': 'Garret',
  'lastName': 'Welland',
  'userName': 'gwellanda',
  'email': 'gwellanda@moonfruit.com',
  'address': '9765 Pawling Pass',
  'phone': '1405818718',
}, {
  'firsName': 'Cami',
  'lastName': 'Huggon',
  'userName': 'chuggonb',
  'email': 'chuggonb@marriott.com',
  'address': '2 Westport Trail',
  'phone': '7704065901',
}, {
  'firsName': 'Randolph',
  'lastName': 'Lovitt',
  'userName': 'rlovittc',
  'email': 'rlovittc@reddit.com',
  'address': '2 Hayes Place',
  'phone': '8449895399',
}, {
  'firsName': 'Amberly',
  'lastName': 'Welfare',
  'userName': 'awelfared',
  'email': 'awelfared@mozilla.org',
  'address': '917 Heath Road',
  'phone': '6336566498',
}, {
  'firsName': 'Max',
  'lastName': 'White',
  'userName': 'mwhitee',
  'email': 'mwhitee@homestead.com',
  'address': '42209 Commercial Crossing',
  'phone': '9917603101',
}, {
  'firsName': 'Aurea',
  'lastName': 'Schaffler',
  'userName': 'aschafflerf',
  'email': 'aschafflerf@de.vu',
  'address': '18000 Toban Road',
  'phone': '3187025421',
}, {
  'firsName': 'Charlton',
  'lastName': 'Tomowicz',
  'userName': 'ctomowiczg',
  'email': 'ctomowiczg@webmd.com',
  'address': '0289 Milwaukee Alley',
  'phone': '6593582363',
}, {
  'firsName': 'Mayne',
  'lastName': 'Richings',
  'userName': 'mrichingsh',
  'email': 'mrichingsh@chron.com',
  'address': '7 Sutteridge Pass',
  'phone': '5083470575',
}, {
  'firsName': 'Lucy',
  'lastName': 'Turland',
  'userName': 'lturlandi',
  'email': 'lturlandi@fc2.com',
  'address': '661 Oak Valley Trail',
  'phone': '5762765897',
}, {
  'firsName': 'Ricky',
  'lastName': 'Bruggeman',
  'userName': 'rbruggemanj',
  'email': 'rbruggemanj@webs.com',
  'address': '9 Village Terrace',
  'phone': '4144402920',
}]);
