db.users.insert([{
  'firsName': 'Staci',
  'lastName': 'Shewon',
  'userName': 'sshewon0',
  'password': 'IcA0G6RYVa',
  'address': '4240 Shelley Court',
  'phone': '125-286-5851',
}, {
  'firsName': 'Laurel',
  'lastName': 'Belk',
  'userName': 'lbelk1',
  'password': '2qvKpxvNA',
  'address': '702 Thackeray Hill',
  'phone': '112-503-1611',
}, {
  'firsName': 'Johannah',
  'lastName': 'Mooney',
  'userName': 'jmooney2',
  'password': 'Jg7GGfbGqq',
  'address': '0299 Dakota Crossing',
  'phone': '357-745-7460',
}, {
  'firsName': 'Shanda',
  'lastName': 'Burgen',
  'userName': 'sburgen3',
  'password': 'cFvPMD8',
  'address': '56899 Old Shore Street',
  'phone': '613-166-7152',
}, {
  'firsName': 'Gilbertina',
  'lastName': 'Beushaw',
  'userName': 'gbeushaw4',
  'password': 'UVq9WpszMq',
  'address': '577 Buell Plaza',
  'phone': '489-792-4066',
}, {
  'firsName': 'Marin',
  'lastName': 'De la Zenne',
  'userName': 'mdelazenne5',
  'password': 'SPZUhgTtD',
  'address': '75 Ludington Lane',
  'phone': '724-800-4869',
}, {
  'firsName': 'Gnni',
  'lastName': 'Beggini',
  'userName': 'gbeggini6',
  'password': 'BidYrvcFwo',
  'address': '0 Old Gate Hill',
  'phone': '333-555-5919',
}, {
  'firsName': 'Cortney',
  'lastName': 'Puddle',
  'userName': 'cpuddle7',
  'password': 'gbDW6r7lR',
  'address': '93495 Garrison Plaza',
  'phone': '841-773-9582',
}, {
  'firsName': 'Darryl',
  'lastName': 'Bettleson',
  'userName': 'dbettleson8',
  'password': 'monVEMV8n',
  'address': '063 John Wall Court',
  'clearclearclearcleaclearcleclearclirclear': 'Esteban',
  'lastName': 'Kempston',
  'userName': 'ekempston9',
  'password': 'S6zhv5s',
  'address': '3765 Fordem Trail',
  'phone': '727-224-1695',
}, {
  'firsName': 'Pauly',
  'lastName': 'Mazey',
  'userName': 'pmazeya',
  'password': '0vmuXMJ8OdCZ',
  'address': '402 Fair Oaks Crossing',
  'phone': '526-141-6989',
}, {
  'firsName': 'Geri',
  'lastName': 'Pyzer',
  'userName': 'gpyzerb',
  'password': 'sRLepvtRJ9',
  'address': '08274 Havey Court',
  'phone': '753-403-5267',
}, {
  'firsName': 'Katie',
  'lastName': 'Sheldon',
  'userName': 'ksheldonc',
  'password': 'kePEBpl',
  'address': '323 Cascade Circle',
  'phone': '474-936-2415',
}, {
  'firsName': 'Gearalt',
  'lastName': 'Bare',
  'userName': 'gbared',
  'password': 'rZOG4fm',
  'address': '1078 Westend Lane',
  'phone': '276-585-5170',
}, {
  'firsName': 'Ernestine',
  'lastName': 'Bignal',
  'userName': 'ebignale',
  'password': '7OxhdxyLzA',
  'address': '89116 Pawling Trail',
  'phone': '845-607-7857',
}, {
  'firsName': 'Muffin',
  'lastName': 'Croot',
  'userName': 'mcrootf',
  'password': '7SfuDH0',
  'address': '68 Autumn Leaf Crossing',
  'phone': '634-477-4147',
}, {
  'firsName': 'Terri',
  'lastName': 'Phelip',
  'userName': 'tphelipg',
  'password': 'nepdio31j9P',
  'address': '2764 Scoville Point',
  'phone': '722-855-2146',
}, {
  'firsName': 'Egbert',
  'lastName': 'Crowley',
  'userName': 'ecrowleyh',
  'password': '8mrsFRrBC2Zg',
  'address': '0 Hauk Avenue',
  'phone': '196-211-4843',
}, {
  'firsName': 'Filmore',
  'lastName': 'Peterson',
  'userName': 'fpetersoni',
  'password': '8o1HyJpBALT',
  'address': '0648 Mcguire Junction',
  'phone': '400-217-5266',
}, {
  'firsName': 'Cordy',
  'lastName': 'Shew',
  'userName': 'cshewj',
  'password': 'iNoYJB9vKpX',
  'address': '42 Namekagon Alley',
  'phone': '109-936-9185',
}, {
  'firsName': 'Eddi',
  'lastName': 'Gumbrell',
  'userName': 'egumbrellk',
  'password': 'BG0PHJwACP',
  'address': '61 Mallard Avenue',
  'phone': '513-834-2420',
}, {
  'firsName': 'Anette',
  'lastName': 'Holsey',
  'userName': 'aholseyl',
  'password': 'mzruCe2yzfl',
  'address': '8052 Laurel Plaza',
  'phone': '261-984-3182',
}, {
  'firsName': 'Esmeralda',
  'lastName': 'Ferri',
  'userName': 'eferrim',
  'password': '0uLFS6u',
  'address': '5594 Daystar Avenue',
  'phone': '316-197-6371',
}, {
  'firsName': 'Amandie',
  'lastName': 'Deme',
  'userName': 'ademen',
  'password': 'yxIhh3fRook',
  'address': '29052 Cody Circle',
  'phone': '548-655-9962',
}, {
  'firsName': 'Corrine',
  'lastName': 'Fender',
  'userName': 'cfendero',
  'password': 'Otghw4',
  'address': '677 Monument Point',
  'phone': '388-587-3536',
}, {
  'firsName': 'Ravi',
  'lastName': 'Margach',
  'userName': 'rmargachp',
  'password': 'GWsYSzyh2G',
  'address': '2003 Village Junction',
  'phone': '521-850-9994',
}, {
  'firsName': 'Elsie',
  'lastName': 'Tripony',
  'userName': 'etriponyq',
  'password': 'OPZ16JGUx',
  'address': '435 Fisk Drive',
  'phone': '726-338-0783',
}, {
  'firsName': 'Hadleigh',
  'lastName': 'Robak',
  'userName': 'hrobakr',
  'password': 'dK5L3hjgu4H',
  'address': '244 Dawn Park',
  'phone': '509-206-0385',
}, {
  'firsName': 'Colver',
  'lastName': 'Layus',
  'userName': 'clayuss',
  'password': 'hRxc3om1avF',
  'address': '7512 Straubel Court',
  'phone': '628-714-7309',
}, {
  'firsName': 'Bertram',
  'lastName': 'Salliss',
  'userName': 'bsallisst',
  'password': 'hNbq5a8cO0E',
  'address': '92118 Bartillon Court',
  'phone': '813-191-4334',
}, {
  'firsName': 'Abbey',
  'lastName': 'Cromley',
  'userName': 'acromleyu',
  'password': 'PvhKx9kO6',
  'address': '13 Haas Lane',
  'phone': '606-139-3217',
}, {
  'firsName': 'Janet',
  'lastName': 'Bonny',
  'userName': 'jbonnyv',
  'password': 'S9aQ0eaXwJd',
  'address': '390 Sundown Drive',
  'phone': '543-283-0385',
}, {
  'firsName': 'Charleen',
  'lastName': 'Full',
  'userName': 'cfullw',
  'password': 'RLNbCG38Ie',
  'address': '10201 Luster Junction',
  'phone': '420-453-5249',
}, {
  'firsName': 'Fanny',
  'lastName': 'Still',
  'userName': 'fstillx',
  'password': 'LSTZWcIxq5J',
  'address': '69 Iowa Place',
  'phone': '737-637-4619',
}, {
  'firsName': 'Mada',
  'lastName': 'Postance',
  'userName': 'mpostancey',
  'password': 'q986Ajb',
  'address': '75 Sauthoff Junction',
  'phone': '884-285-6265',
}, {
  'firsName': 'Pris',
  'lastName': 'Sallows',
  'userName': 'psallowsz',
  'password': 'nJjHyj8fgl',
  'address': '41 Milwaukee Terrace',
  'phone': '352-717-0303',
}, {
  'firsName': 'Der',
  'lastName': 'Cliss',
  'userName': 'dcliss10',
  'password': 'JsBJpcvgbX',
  'address': '8 Havey Junction',
  'phone': '783-920-5788',
}, {
  'firsName': 'Kimberli',
  'lastName': 'Renahan',
  'userName': 'krenahan11',
  'password': 'RxYopv',
  'address': '59 Corry Point',
  'phone': '887-631-3001',
}, {
  'firsName': 'Lani',
  'lastName': 'Verissimo',
  'userName': 'lverissimo12',
  'password': 'e6fawGN',
  'address': '9 Waubesa Plaza',
  'phone': '395-611-3416',
}, {
  'firsName': 'Pamelina',
  'lastName': 'Pauleau',
  'userName': 'ppauleau13',
  'password': 'ptt4Bzx4a',
  'address': '95735 Dottie Court',
  'phone': '650-808-2602',
}, {
  'firsName': 'Cordell',
  'lastName': 'Lardiner',
  'userName': 'clardiner14',
  'password': 'bJ9zOOnUZ',
  'address': '986 Bartelt Lane',
  'phone': '945-834-0640',
}, {
  'firsName': 'Michell',
  'lastName': 'Yedall',
  'userName': 'myedall15',
  'password': 'H1B9pY',
  'address': '6862 Lunder Pass',
  'phone': '132-426-0592',
}, {
  'firsName': 'Fran',
  'lastName': 'Bufton',
  'userName': 'fbufton16',
  'password': 'xUQBQyh',
  'address': '55185 Dryden Place',
  'phone': '623-132-3748',
}, {
  'firsName': 'Olenka',
  'lastName': 'Birchner',
  'userName': 'obirchner17',
  'password': 'bCOvMvt162BK',
  'address': '825 Trailsway Plaza',
  'phone': '101-889-3740',
}, {
  'firsName': 'Ilyse',
  'lastName': 'Pinckard',
  'userName': 'ipinckard18',
  'password': 'FI27x1Dlp',
  'address': '06922 Fairfield Parkway',
  'phone': '222-937-6616',
}, {
  'firsName': 'Avis',
  'lastName': 'Gadaud',
  'userName': 'agadaud19',
  'password': 'XGPrwZaFXw',
  'address': '635 Springs Pass',
  'phone': '414-820-5800',
}, {
  'firsName': 'Annabella',
  'lastName': 'Merrifield',
  'userName': 'amerrifield1a',
  'password': 'DdwVWa',
  'address': '81296 Sherman Avenue',
  'phone': '605-860-2833',
}, {
  'firsName': 'Elianore',
  'lastName': 'Cruden',
  'userName': 'ecruden1b',
  'password': 'RP6IyOdMiHK',
  'address': '205 Golf Course Avenue',
  'phone': '479-837-6904',
}, {
  'firsName': 'Ailina',
  'lastName': 'Umbert',
  'userName': 'aumbert1c',
  'password': 'OVUSh7BS',
  'address': '559 Cordelia Way',
  'phone': '302-297-3018',
}, {
  'firsName': 'Arny',
  'lastName': 'Dennidge',
  'userName': 'adennidge1d',
  'password': 'AUuhSI',
  'address': '10 Prentice Drive',
  'phone': '591-395-4275',
}]);
