db.users.insert([{
  'firsName': 'Danika',
  'lastName': 'Seamer',
  'userName': 'dseamer0',
  'password': 'DT2RiQp',
  'email': 'dseamer0@sina.com.cn',
  'address': '90918 Northridge Parkway',
  'phone': '5018301709',
}, {
  'firsName': 'Kelila',
  'lastName': 'Ellul',
  'userName': 'kellul1',
  'password': '7iBhdGxK',
  'email': 'kellul1@ebay.co.uk',
  'address': '95 Clyde Gallagher Road',
  'phone': '4375704194',
}, {
  'firsName': 'Friederike',
  'lastName': 'Hubane',
  'userName': 'fhubane2',
  'password': 'Plc5FhEUINb',
  'email': 'fhubane2@vimeo.com',
  'address': '45514 Main Way',
  'phone': '6297967939',
}, {
  'firsName': 'Davey',
  'lastName': 'Raymont',
  'userName': 'draymont3',
  'password': 'Jmr1hW0',
  'email': 'draymont3@state.tx.us',
  'address': '4 Judy Park',
  'phone': '1088206722',
}, {
  'firsName': 'Sibella',
  'lastName': 'Cakes',
  'userName': 'scakes4',
  'password': 'qRxOp7ySKl5',
  'email': 'scakes4@usa.gov',
  'address': '4202 Butternut Junction',
  'phone': '4186088068',
}, {
  'firsName': 'Patrizia',
  'lastName': 'Witherden',
  'userName': 'pwitherden5',
  'password': 'WByi7yuB',
  'email': 'pwitherden5@4shared.com',
  'address': '7880 Shoshone Plaza',
  'phone': '8581259037',
}, {
  'firsName': 'Baxy',
  'lastName': 'Littell',
  'userName': 'blittell6',
  'password': 'hcBH4HEEYPez',
  'email': 'blittell6@wordpress.com',
  'address': '11 Hoffman Way',
  'phone': '9166406142',
}, {
  'firsName': 'Gayle',
  'lastName': 'O\' Mullan',
  'userName': 'gomullan7',
  'password': 'JLvYX50WReW',
  'email': 'gomullan7@furl.net',
  'address': '5153 Dryden Trail',
  'phone': '8543692699',
}, {
  'firsName': 'Creighton',
  'lastName': 'Turney',
  'userName': 'cturney8',
  'password': 'gaZcEZy4',
  'email': 'cturney8@ted.com',
  'address': '0301 Transport Circle',
  'phone': '7838722329',
}, {
  'firsName': 'Janetta',
  'lastName': 'Barnsdale',
  'userName': 'jbarnsdale9',
  'password': 'TttM5Cbeiae',
  'email': 'jbarnsdale9@zdnet.com',
  'address': '20699 Bayside Park',
  'phone': '7857214515',
}, {
  'firsName': 'Isacco',
  'lastName': 'Hardin',
  'userName': 'ihardina',
  'password': 'bXIIqYF6',
  'email': 'ihardina@smh.com.au',
  'address': '97279 Lien Parkway',
  'phone': '9215766007',
}, {
  'firsName': 'Jimmy',
  'lastName': 'Andryszczak',
  'userName': 'jandryszczakb',
  'password': 'WUpHetaxT',
  'email': 'jandryszczakb@phoca.cz',
  'address': '79236 Lillian Place',
  'phone': '5122108591',
}, {
  'firsName': 'Aksel',
  'lastName': 'Jellman',
  'userName': 'ajellmanc',
  'password': 'TRllZ7uYXFiT',
  'email': 'ajellmanc@pen.io',
  'address': '4891 Vidon Center',
  'phone': '6775066133',
}, {
  'firsName': 'Ninon',
  'lastName': 'Prall',
  'userName': 'npralld',
  'password': 'M9eRqNb',
  'email': 'npralld@4shared.com',
  'address': '44186 Leroy Avenue',
  'phone': '8968038571',
}, {
  'firsName': 'Tiphany',
  'lastName': 'Seacroft',
  'userName': 'tseacrofte',
  'password': 'bM2ILT',
  'email': 'tseacrofte@psu.edu',
  'address': '4763 Red Cloud Crossing',
  'phone': '9541699482',
}, {
  'firsName': 'Addie',
  'lastName': 'Brick',
  'userName': 'abrickf',
  'password': '9Uz0e4q',
  'email': 'abrickf@omniture.com',
  'address': '59563 Almo Plaza',
  'phone': '3843362630',
}, {
  'firsName': 'Ody',
  'lastName': 'Chatenier',
  'userName': 'ochatenierg',
  'password': 'Ls4VLLLn9r',
  'email': 'ochatenierg@guardian.co.uk',
  'address': '18193 Mockingbird Center',
  'phone': '5186085686',
}, {
  'firsName': 'Elinor',
  'lastName': 'Hakeworth',
  'userName': 'ehakeworthh',
  'password': 'hLtd8EkwVY1',
  'email': 'ehakeworthh@wunderground.com',
  'address': '56 Esker Parkway',
  'phone': '5123353178',
}, {
  'firsName': 'Wilma',
  'lastName': 'Shapland',
  'userName': 'wshaplandi',
  'password': 't3vOgy6',
  'email': 'wshaplandi@tinypic.com',
  'address': '16876 Debra Way',
  'phone': '7079201735',
}, {
  'firsName': 'Melony',
  'lastName': 'Capp',
  'userName': 'mcappj',
  'password': 'FGrVGI',
  'email': 'mcappj@webmd.com',
  'address': '38 Graceland Court',
  'phone': '1826231340',
}]);
